CREATE TABLE words (
   word_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   word_to_learn    VARCHAR(255) NOT NULL,
   description      VARCHAR(255),
   translation      VARCHAR(255),
   category         VARCHAR(255) NOT NULL,
   word_status      VARCHAR(255) NOT NULL,
   counter          INTEGER NOT NULL,
   time_stamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_words PRIMARY KEY (word_id)
);