CREATE TABLE sentence (
  sentence_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   sentence_with_word VARCHAR(255),
   word_id BIGINT,
   CONSTRAINT pk_sentence PRIMARY KEY (sentence_id)
);

ALTER TABLE sentence ADD CONSTRAINT FK_SENTENCE_ON_WORD FOREIGN KEY (word_id) REFERENCES words (word_id);